aws:
  ec2:
    cpu_utilization:
      namespace: AWS/EC2
      metric_name: CPUUtilization
      statistic: Average
      period: 300

    cpu_max:
      namespace: AWS/EC2
      metric_name: CPUUtilization
      statistic: Maximum
      period: 300

    network_in_bytes:
      namespace: AWS/EC2
      metric_name: NetworkIn
      statistic: Sum
      period: 300

    network_out_bytes:
      namespace: AWS/EC2
      metric_name: NetworkOut
      statistic: Sum
      period: 300

    status_failed_system:
      namespace: AWS/EC2
      metric_name: StatusCheckFailed_System
      statistic: Maximum
      period: 300

    cpu_credit_balance:
      namespace: AWS/EC2
      metric_name: CPUCreditBalance
      statistic: Average
      period: 300

  s3:
    bucket_size_bytes:
      namespace: AWS/S3
      metric_name: BucketSizeBytes
      statistic: Average
      period: 86400
      storage_type: StandardStorage

    number_of_objects:
      namespace: AWS/S3
      metric_name: NumberOfObjects
      statistic: Average
      period: 86400
      storage_type: AllStorageTypes

  lambda:
    invocations:
      namespace: AWS/Lambda
      metric_name: Invocations
      statistic: Sum
      period: 300

    errors:
      namespace: AWS/Lambda
      metric_name: Errors
      statistic: Sum
      period: 300

    throttles:
      namespace: AWS/Lambda
      metric_name: Throttles
      statistic: Sum
      period: 300

    duration_avg:
      namespace: AWS/Lambda
      metric_name: Duration
      statistic: Average
      period: 300

    duration_max:
      namespace: AWS/Lambda
      metric_name: Duration
      statistic: Maximum
      period: 300

    concurrent_executions:
      namespace: AWS/Lambda
      metric_name: ConcurrentExecutions
      statistic: Maximum
      period: 300

  cwagent:
    memory_used_percent:
      namespace: CWAgent
      metric_name: mem_used_percent
      statistic: Average
      period: 300
      requires_agent: true

    disk_used_percent:
      namespace: CWAgent
      metric_name: disk_used_percent
      statistic: Average
      period: 300
      requires_agent: true